### ISSUE TITLE
Uninitialized Constant PyCall::LibPython::Helpers

### ISSUE THREAD

**Issue by taylorkrause** [mrkn/pycall.rb#119]
Anyone ever seen this before after deploying to production on Heroku? Works fine locally, just not once deployed :/

**Comment by dsounded** [comment]
Hello @taylorkrause 
Are you using this successfully on Heroku ?
Could you please help with https://github.com/mrkn/pycall.rb/issues/62 ?

**Comment by Tshamp7** [comment]
> Anyone ever seen this before after deploying to production on Heroku? Works fine locally, just not once deployed :/

did you figure out what was wrong? Im having the same error.

**Comment by MuthukkaruppanSubramanian** [comment]
Is there any solution for this in Ruby

**Comment by MuthukkaruppanSubramanian** [comment]
irb(main):001:0> require 'pycall/import'
=> true
irb(main):002:0> include PyCall::Import
=> Object

irb(main):006:0> pyimport :math
Traceback (most recent call last):
        4: from C:/Ruby25-x64/bin/irb.cmd:19:in `<main>'
        3: from (irb):6
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/pycall-1.4.0/lib/pycall/import.rb:18:in `pyimport'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/pycall-1.4.0/lib/pycall.rb:73:in `import_module'
NameError (uninitialized constant PyCall::LibPython::Helpers)

**Comment by Tshamp7** [comment]
> Is there any solution for this in Ruby

You need to use a third party build pack with python shared libraries, and make sure to clear your build cache on heroku after removing the default python build pack.
