### ISSUE TITLE
How to import class with pyfrom?

### ISSUE THREAD

**Issue by shamscorner** [mrkn/pycall.rb#124]
I want to import this, 
`pyfrom :'sklearn.preprocessing', import: :PolynomialFeatures`

But it is giving me this error, 
`undefined method `module_eval'`

Can anybody help me with this? Am I missing something here?

**Comment by lesliebinbin** [comment]
probably should be pyfrom 'sklearn.preprocessing', import: 'PolynomialFeatures' as from the example https://github.com/mrkn/pycall.rb/blob/master/examples/plot_forest_importances_faces.rb, 
pyfrom 'sklearn.ensemble', import: 'ExtraTreesClassifier'

**Comment by shamscorner** [comment]
I tried with that solution but for some reason, it was not working. I solved this way though, 

`pyimport :'sklearn.preprocessing', as: :preprocessing`

and then 

`poly = preprocessing.PolynomialFeatures.new(degree=4)`

Ok, thanks for your reply. I will try to look at why the solution you mentioned was not working. I am closing this thread.

**Comment by alexeevit** [comment]
Ran into the same problem. If just in console I do `pyfrom 'deepface', import: 'DeepFace'` everything works fine. Once I created a class and call `pyfrom` in initializer, it crashes with the error:

```
/usr/local/bundle/ruby/3.2.0/gems/pycall-1.5.1/lib/pycall/import.rb:88:in `define_name': undefined method `module_eval' for #<DeepFaceFacade:0x0000ffffa42a5388 @assoc_array_matcher=#<Proc:0x0000ffffa42a5108 /usr/local/bundle/ruby/3.2.0/gems/pycall-1.5.1/lib/pycall/import.rb:107 (lambda)>> (NoMethodError)

          context.module_eval { const_set(name, pyobj) }
                 ^^^^^^^^^^^^
```
