### ISSUE TITLE
PyCall::LibPythonFunctionNotFound (Unable to find the required symbol in libpython: _Py_NoneStruct)

### ISSUE THREAD

**Issue by ljoglar** [mrkn/pycall.rb#149]
Hi! 
I really would love to be able to use your library for a project, but I can't seem to make it work, not even with the simplest example... Any help on what I'm missing would be great.

Thanks in advance!

Luis.
```
xxxxx@xxxxx:~/projects/ruby$ irb
irb(main):001:0> require 'pycall/import'
=> true
irb(main):002:0> include PyCall::Import
=> Object
irb(main):003:0> pyimport :math
Traceback (most recent call last):
       10: from /usr/bin/irb:23:in '<main>'
        9: from /usr/bin/irb:23:in 'load'
        8: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in '<top (required)>'
        7: from (irb):3
        6: from /var/lib/gems/2.7.0/gems/pycall-1.4.1/lib/pycall/import.rb:18:in 'pyimport'
        5: from /var/lib/gems/2.7.0/gems/pycall-1.4.1/lib/pycall.rb:74:in 'import_module'
        4: from /var/lib/gems/2.7.0/gems/pycall-1.4.1/lib/pycall/init.rb:16:in 'const_missing'
        3: from /var/lib/gems/2.7.0/gems/pycall-1.4.1/lib/pycall/init.rb:39:in 'init'
        2: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in 'require'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in 'require'
PyCall::LibPythonFunctionNotFound (Unable to find the required symbol in libpython: _Py_NoneStruct)
```

**Comment by buncis** [comment]
ah I have same error when trying to deploy to heroku

**Comment by buncis** [comment]
sorry if its not answering the original question

but since its have save error message

I manage to fix my problem in heroku 
by using heroku-18 stack

this buildpacks https://github.com/ReforgeHQ/heroku-buildpack-python
with python 3.8.1

**Comment by buncis** [comment]
@ljoglar  make sure your python have --enable-shared 
to check it first run this on your bash/terminal
`python3 -msysconfig | grep enable-shared`

if there is no result that show --enable-shared on your python

you need to recompile ur python with --enable-shared

**Comment by bcdavasconcelos** [comment]
@buncis, could you detail how you managed to recompile your py interpreter with `--enable-shared`? I spent many hours trying to do so in my M1 mac but failed miserably.

**Comment by buncis** [comment]
@bcdavasconcelos I explain my solution on #151
