### ISSUE TITLE
exceptions not raised from within without_gvl block

### ISSUE THREAD

**Issue by amcox** [mrkn/pycall.rb#154]
When an exception, whether from a python or ruby function, is encountered within a without_gvl block, PyCall discards the exception and returns nil instead of raising the exception.

For example:

```
math = PyCall.import_module("math")
math.factorial(-1)
# raises an exception PyCall::PyError: <class 'ValueError'>: factorial() not defined for negative values 

PyCall.without_gvl do math.factorial(-1) end
# returns nil without raising an exception
```

I would expect the exception to be raised when exiting the block.

**Comment by mrkn** [comment]
@amcox Thank you for reporting this.  Good catch.  I'll fix it soon.
