### ISSUE TITLE
Segmentation fault ( Pycall [BUG] Segmentation fault at 0x0000000000000010 )

### ISSUE THREAD

**Issue by mAreebAlam** [mrkn/pycall.rb#183]
there is problem in the method import_module of file "pycall-1.5.2/lib/pycall.rb"

def import_module(name)
LibPython::Helpers.import_module(name)
end

it calls a c method in this file "ext/pycall/pycall.c"

# C language method

static VALUE
pycall_libpython_helpers_m_import_module(int argc, VALUE *argv, VALUE mod)
{
VALUE name, globals, locals, fromlist, level;
char const *name_cstr;

rb_scan_args(argc, argv, "14", &name, &globals, &locals, &fromlist, &level);

if (RB_TYPE_P(name, T_SYMBOL)) {
name = rb_sym_to_s(name);
}

name_cstr = StringValueCStr(name);

if (argc == 1) {
return pycall_import_module(name_cstr);
}

if (argc == 5) {
level = rb_check_to_integer(level, "to_int");
}
else {
/* TODO: set the default level to 0 */
}

return pycall_import_module_level(name_cstr, globals, locals, fromlist, NUM2INT(level));
}

which again calls the previous method and the process continues in an infinite loop, hence segmentation fault occurs

**Comment by snickell** [comment]
I don't think there is a loop here, I have traced the code like this, I do not see any loops:
- LibPython::Helpers.import_module(name)
  - calls rb_define_module_function(mHelpers, "import_module", pycall_libpython_helpers_m_import_module, -1);
    - calls pycall_libpython_helpers_m_import_module
      - calls pycall_import_module
        - calls libpython: Py_API(PyImport_ImportModule): NO LOOP
      - calls pycall_import_module_level
        - calls Py_API(PyImport_ImportModuleLevel): NO LOOP

Are you using Rails or Puma? If so, PyCall is NOT safe to call from a web request, even if puma/rails has threads set to 1. Do you have threads in your application?

I suspect this might be the same issue as:
- https://github.com/mrkn/pycall.rb/issues/185
- https://github.com/mrkn/pycall.rb/issues/175

**Comment by snickell** [comment]
See: https://github.com/mrkn/pycall.rb/issues/96

**Comment by mAreebAlam** [comment]
Thanks for clarification
I think you are right, the issue is due to puma

**Comment by snickell** [comment]
@mAreebAlam I'm working on an approach for working with Puma, let me know if you want me to ping you when its working
