### ISSUE TITLE
RubyDataScience

### ISSUE THREAD

**Issue by arbox** [mrkn/pycall.rb#23]
Dear @mrkn  ,

we've recently added `pycall`  to our upcoming RubyDataScience list: https://github.com/arbox/data-science-with-ruby

In order to connect all Ruby & Data Science related projects we introduced the `rubydatascience` topic on GitHub.

Please consider adding this topic to your repository as well so that the Ruby community can discover this project faster :smiley: The `rubyml` topic could be of high relevance for you too.

Thank you in advance!

**Comment by mrkn** [comment]
Done.
