### ISSUE TITLE
Calling Python modules 

### ISSUE THREAD

**Issue by peterzhu2118** [mrkn/pycall.rb#47]
How can I import a Python module that I wrote myself? If I have `somemodule.py`, doing `pyimport 'somemodule'` does not work as it throws a `PyCall::PyError: <type 'exceptions.ImportError'>: No module named somemodule` error.

**Comment by mrkn** [comment]
@peterzhu2118 Add the directory that contains your `somemodule.py` into `PyCall.sys.path` like:

```
PyCall.sys.path.append(path_to_directory_of_somemodule_py)
```
