### ISSUE TITLE
Symbol not found _main (PyCall::PyError)

### ISSUE THREAD

**Issue by tayeb83** [mrkn/pycall.rb#48]
I use Pycall to call sklearn:
require 'pycall/import'
include PyCall::Import

pyfrom :sklearn, import: :datasets

I got this error:

/usr/local/lib/ruby/gems/2.4.0/gems/pycall-1.0.3/lib/pycall/import.rb:46:in `import_module’: : dlopen(/Users/tay/anaconda3/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-36m-darwin.so, 2): Symbol not found: _main (PyCall::PyError)

thnks

**Comment by mrkn** [comment]
@tayeb83 I couldn't reproduce this issue.
I used Ruby 2.5.0, Python 3.6.1 installed by pyenv, pycall 1.0.3, and scikit-learn 0.19.1.
