### ISSUE TITLE
PyCall::PythonNotFound with usage example

### ISSUE THREAD

**Issue by avigard** [mrkn/pycall.rb#52]
Hello guys,

I have _Ruby 2.4.3p205_ and _Python 3.6.2_ on my _Windows 8.1_ machine installed.
I tried to run the usage example which compares Python's math.sin with Ruby's Math.sin.

I get a _PyCall::PythonNotFound_ exception on the line where it says _pyimport :math_.

Can somebody may help me with this?

**Comment by mrkn** [comment]
Show your code as is.

And, to investigate the reason why pycall cannot find python, show the value of the environment variable PATH, and try the same code with the environment variable `PYCALL_DEBUG_FIND_LIBPYTHON=1`.

**Comment by golirev** [comment]
I got the same error without adding PATH setting for Python environment.

ex.
set PATH=C:\Anaconda3;C:\Anaconda3\Library\mingw-w64\bin;C:\Anaconda3\Library\usr\bin;C:\Anaconda3\Library\bin;C:\Anaconda3\Scripts;%PATH%

If you use RubyInstaller2, you also need to set RUBY_DLL_PATH environment variable.
Without RUBY_DLL_PATH setting,  I got 'DLL load failed' ... (PyCall::PyError) when I use scikit-learn, etc.

ex.
set RUBY_DLL_PATH=%PATH%

**Comment by mrkn** [comment]
@avigard Please re-open if you want to continue this issue.

**Comment by wchinnapper** [comment]
With: PYCALL_DEBUG_FIND_LIBPYTHON=1

Fast Debugger (ruby-debug-ide 0.7.0.beta6, debase 0.2.3.beta2, file filtering is supported) listens on 0.0.0.0:57273
DEBUG(find_libpython) find_libpython(nil)
DEBUG(find_libpython) investigate_python_config("python")
DEBUG(find_libpython) libs: ["python37", "python"]
DEBUG(find_libpython) libpaths: ["C:\\Users\\774782\\AppData\\Local\\Programs\\Python\\Python37-32", "C:\\Users\\774782\\AppData\\Local\\Programs\\Python\\Python37-32", "C:\\Users\\774782\\AppData\\Local\\Programs\\Python\\Python37-32/lib"]
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/python37
DEBUG(find_libpython) Fiddle::DLError: Exec format error
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/python37
DEBUG(find_libpython) Fiddle::DLError: Exec format error
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/lib/python37
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/lib/python37.dll
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/python
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/python.dll
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/python
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/python.dll
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/lib/python
DEBUG(find_libpython) Unable to find C:\Users\774782\AppData\Local\Programs\Python\Python37-32/lib/python.dll
DEBUG(find_libpython) Fiddle::DLError: Exec format error
DEBUG(find_libpython) Fiddle::DLError: No such file or directory
Uncaught exception: PyCall::PythonNotFound
