### ISSUE TITLE
newspaper library is not working

### ISSUE THREAD

**Issue by umlx5h** [mrkn/pycall.rb#53]
I want to use newspaper library for my rails project.  
So I tried to use this gem but I got an error.

This is my code

```
require 'pycall/import'
include PyCall::Import

pyimport 'newspaper'

url = 'http://www.bbc.co.uk/zhongwen/simp/chinese_news/2012/12/121210_hongkong_politics.shtml'

article = newspaper.Article(url)
article.download()
article.parse()
print(article.text)
```

I got a following error
```
~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pycall-1.0.3/lib/pycall/pyobject_wrapper.rb:43:in `download': <class 'TypeError'>: download() missing 1 required positional argument: 'self' (PyCall::PyError)  
        from ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pycall-1.0.3/lib/pycall/pyobject_wrapper.rb:43:in `method_missing'
        from newspaper.rb:9:in `<main>'
```

Other libraries like math, pandas are working.  
I have no idea if this is caused due to this gem, But native python code can be working.

 
OS: OSX High Sierra  
Python: 3.6.4  
Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16  
echo $PYTHON => /usr/local/bin/python3  
newspaper3k (0.2.5)  
pycall (1.0.3)

**Comment by mephistobooks** [comment]
Hi. change your code `newspaper.Article(url)` to `newspaper.Article.new(url)` or `newspaper.Article.(url)` (dot after Article).

**Comment by mrkn** [comment]
@umlx5h Rewrite `newspaper.Article(url)` to `newspaper.Article.new(url)` as @mephistobooks said.

@mephistobooks Thank you for your assistance.
