### ISSUE TITLE
Can't call a method on a imported module

### ISSUE THREAD

**Issue by frenesim** [mrkn/pycall.rb#55]
My environment is 
`$ uname -a`
Linux b22 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

`$ lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

Python 3.6.3
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
pycall (1.0.3)
numpy (1.14.0) 
scikit-learn (0.19.1)        
scipy (1.0.0)                
sklearn (0.0)    

I'm following the first steps in support vector machine from [scikit-learn](http://scikit-learn.org/stable/modules/svm.html) in a ruby console.

Here is the piece of code I ran:
 `pyfrom :sklearn, import: :svm`
`X = [[0, 0], [1, 1]]`
`y = [0, 1]`
`clf = svm.SVC()`
`clf.fit(X, y)`

I manage to import all libraries, but then it fails with:
PyCall::PyError: <class 'TypeError'>: fit() missing 1 required positional argument: 'y'

This lead me to solutions where is mentioned to add parentheses when instantiating the class, but i'm not able to make it work.

I get the same error with:
`clf.fit([[0,0],[1,1]], [0,1])`

Can you help pls

**Comment by mephistobooks** [comment]
Hi, I am not the author of this, but `svm.SVC()` is the cause of this PyError. This not a instance object but a class (sv.SVC().class => Class).

The solution is simply write `clf=svm.SVC.new()` or `clf=svm.SVC.()` (dot after SVC), I guess you can get what you want.

**Comment by mrkn** [comment]
@mephistobooks Thank you for your assistance.  You are right.  And I recommend to use `new` instead of `.()` because it is Ruby's way of instantiation.

@frenesim Rewrite your code by using `SVC.new`.

**Comment by frenesim** [comment]
@mephistobooks Thanks for your help. I was stuck in trying pyhton syntax which it's not the way.
@mrkn Great work with this gem.
