### ISSUE TITLE
"no implicit conversion of Object into String (TypeError)" on pyobject_wrapper.rb:43:in

### ISSUE THREAD

**Issue by mikisvaz** [mrkn/pycall.rb#56]
Hi,

I've been trying to use tensorflow through pycall.rb and I found the following error:

> /home/mvazque2/.rvm/gems/ruby-2.4.1/gems/pycall-1.0.3/lib/pycall/pyobject_wrapper.rb:43:in `run': no implicit conversion of Object into String (TypeError)
        from /home/mvazque2/.rvm/gems/ruby-2.4.1/gems/pycall-1.0.3/lib/pycall/pyobject_wrapper.rb:43:in `method_missing'
        from pycal.tf.rb:21:in `<main>'

The code is the following:

```ruby

require 'pycall/import'
include PyCall::Import

pyimport :tensorflow

tf = tensorflow

a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)

# Define some operations
add = tf.add(a, b)

sess = tf.Session.new()
sess.run(add, feed_dict={a =>  2, b => 3})
```
I'm unable to track this error further, I cannot see where is this implicit conversion attempted.

**Comment by mrkn** [comment]
@mikisvaz rewrite the syntax of keyword argument at the last line in Ruby-style:

```
sess.run(add, feed_dict: {a =>  2, b => 3})
```

**Comment by mikisvaz** [comment]
Yes, that worked. Thanks!
