### ISSUE TITLE
Check and update AppVayer setting

### ISSUE THREAD

**Issue by mrkn** [mrkn/pycall.rb#60]
- [ ] Ruby 2.5
- [ ] [Recent failures](https://ci.appveyor.com/project/mrkn/pycall/build/1.0.123)

**Comment by olleolleolle** [comment]
(Right, and there's something about the build status badge in the README, too. It says project not found when I visited its link.)

**Comment by mrkn** [comment]
@olleolleolle Good catch! Thank you.
