### ISSUE TITLE
[question] passing iterable object in ruby 

### ISSUE THREAD

**Issue by drselump14** [mrkn/pycall.rb#61]
The methods that I want to use requires iterable to be passed as argument. 
I've tried to pass a simple Ruby array into it, but it still produces error.

Any help will be appreciated ... Thanks

**Comment by drselump14** [comment]
It looks like I have to use Constructor.new when calling python Constructor ... sorry, it's my bad ... close this issue ...

**Comment by mrkn** [comment]
@drselump14 No problem.  Don't hesitate to ask me if you have new questions :wink:
