### ISSUE TITLE
Can't import CountVectorizer from 'sklearn.feature_extraction.text

### ISSUE THREAD

**Issue by rahmatullah5** [mrkn/pycall.rb#73]
I am having an issue (undefined method module_eval when trying to import CountVectorizer from sklearn.feature_extraction.text.
My Code:
`    pyfrom :'sklearn.feature_extraction.text', import: :CountVectorizer
`

![image](https://user-images.githubusercontent.com/16495060/45398054-e933a800-b66c-11e8-9e8e-70260b38b17b.png)

Am I missing something, or is this library not supported yet on pycall?

**Comment by shamscorner** [comment]
Then how can I import this?
`pyfrom :'sklearn.preprocessing', import: :PolynomialFeatures`
