### ISSUE TITLE
importing cv2 python module

### ISSUE THREAD

**Issue by raphaelfarzankashani** [mrkn/pycall.rb#97]
Hi @mrkn - using the following code i was able to create a ruby script that successfully ran methods from the Python opencv (cv2) library (https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_tutorials.html):
`pyimport :numpy, as: :np
pyimport :math
pyimport :os
pyimport :cv2
pyimport :matplotlib, as: :mp
pyimport :pytesseract`

For example would call the following methods:
`@im = cv2.imread(cv2.samples.findFile(file))
@imgray = cv2.cvtColor(@im,cv2.COLOR_BGR2GRAY)`

So far so good.

Unfortunately though, when I tried to run these methods within my rails app, I started getting errors - e.g. "NameError: undefined local variable or method `cv2'"

I then added/declared a variable for the cv2 module to be called in other methods - i.e., 
`cv2 = PyCall.import_module('cv2')`, but then cv2 returned nil and I received the following error: 
`NoMethodError: undefined method `samples' for nil:NilClass`

Any guidance on integrating this cv2 library into the rails app?

Thanks very much

**Comment by mrkn** [comment]
@raphaelfarzankashani Please show me the code to reproduce your problem.

**Comment by raphaelfarzankashani** [comment]
@mrkn all set actually figured it out - thanks a ton man
